#REAL VERSION
# application: pickmeup-telegram
# version: 11

#TEST DEV
#application: tiramisu-telegram
#version: 1

runtime: python27
api_version: 1
threadsafe: false

#inbound_services:
#- channel_presence

builtins:
- remote_api: on
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /set_webhook
  login: admin
  script: main.app

- url: /get_webhook_info
  login: admin
  script: main.app

- url: /delete_webhook
  login: admin
  script: main.app

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /ttdata
  static_dir: ttdata
  application_readable: true

- url: /data
  static_dir: data
  application_readable: true

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest
